# coding: utf-8

"""
    Webshipper V2 REST API

       <p>     The Webshipper API is a RESTful JSON API that gives full control over your Webshipper account. The API is scoped to your <em>account name</em>,     and is accessed via the endpoint <em>https://&lt;account name&gt;.api.webshipper.io/v2/</em>. Your <em>account name</em> is the same as you see when you access the Webshipper web UI     at <em>https://&lt;account name&gt;.webshipper.io</em>.   </p>    <p>     This API conforms to the <a href=\"http://jsonapi.org/\">JSON API standard</a> with the following conventions:     <ul>       <li>Resources are identified with the attribute <code>id</code>, which is a server-side generated sequential integer</li>       <li>Resource types are pluralised and underscored, like <code>order_lines</code></li>       <li>The API has a fixed page limit of 30 records. To fetch more records use the query parameter <code>page[number]</code></li>       <li>All resources have the attributes <code>created_at</code> and <code>updated_at</code> which are ISO 8601 timestamps like <code>2018-03-07T14:01:18.000Z</code> </li>       <li>All country codes are <a href=\"https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2\">ISO 3166-1 alpha-2</a> codes</li>     </ul>   </p>     <p> It is also possible to download the documentation in the OpenAPI 3.0 <a href=\"?download_openapi=1\">here</a> </p>    <div class=\"alert alert-info\">     <i class=\"fa fa-info mr-2\"></i>     Webshipper <em>strongly</em> recommends using a client library for utilising this API. Refer to jsonapi.org's list of     <a href=\"http://jsonapi.org/implementations/#client-libraries\">jsonapi.org's list of client libraries</a> to find one for your language.   </div> 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.shipments_id_get200_response_included_inner_data import ShipmentsIdGet200ResponseIncludedInnerData

class TestShipmentsIdGet200ResponseIncludedInnerData(unittest.TestCase):
    """ShipmentsIdGet200ResponseIncludedInnerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShipmentsIdGet200ResponseIncludedInnerData:
        """Test ShipmentsIdGet200ResponseIncludedInnerData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShipmentsIdGet200ResponseIncludedInnerData`
        """
        model = ShipmentsIdGet200ResponseIncludedInnerData()
        if include_optional:
            return ShipmentsIdGet200ResponseIncludedInnerData(
                alias = '',
                services = '',
                attrs = '',
                prefer_zpl = True,
                created_at = '',
                updated_at = '',
                is_approved = True,
                approved_service_codes = '',
                service_parameter_enums = '',
                barcode_notification_behavior = 56,
                barcode_notification_mail = '',
                has_active_cost_sheet = '',
                delete_at_carrier = True,
                test_mode = True,
                logo = '',
                logo_url = '',
                print_error_label = True,
                ftp_configuration_id = 56,
                order_channel_id = 56,
                status = '',
                ext_ref = '',
                visible_ref = '',
                drop_point = '',
                original_shipping = openapi_client.models.original_shipping.original_shipping(),
                order_lines = [
                    openapi_client.models.order_lines.order_lines(
                        sku = '', 
                        description = '', 
                        quantity = 56, 
                        location = '', 
                        tarif_number = '', 
                        country_of_origin = '', 
                        unit_price = 1.337, 
                        package_id = 56, 
                        discounted_unit_price = '', 
                        discount_value = 1.337, 
                        discount_type = 56, 
                        vat_percent = 1.337, 
                        order_id = 56, 
                        status = 56, 
                        ext_ref = '', 
                        weight = 1.337, 
                        weight_unit = '', 
                        created_at = '', 
                        updated_at = '', 
                        is_virtual = True, 
                        dangerous_goods_details = openapi_client.models.dangerous_goods_details.dangerous_goods_details(), )
                    ],
                delivery_address = openapi_client.models.delivery_address.delivery_address(),
                sender_address = openapi_client.models.sender_address.sender_address(),
                billing_address = openapi_client.models.billing_address.billing_address(),
                sold_from_address = openapi_client.models.shipping_addresses.shipping_addresses(
                    att_contact = '', 
                    company_name = '', 
                    address_1 = '', 
                    address_2 = '', 
                    country_code = '', 
                    state = '', 
                    phone = '', 
                    email = '', 
                    zip = '', 
                    city = '', 
                    vat_no = '', 
                    address_type = '', 
                    ext_location = '', 
                    voec = '', 
                    eori = '', 
                    sprn = '', 
                    ioss = '', 
                    fda = '', 
                    duns = '', 
                    personal_customs_no = '', 
                    company_customs_numbers = '', ),
                currency = '',
                internal_comment = '',
                external_comment = '',
                error_message = '',
                slip = '',
                var_base64 = '',
                lock_state = '',
                source = 56,
                tags = [
                    ''
                    ],
                error_class = '',
                slip_printed = True,
                label_printed = True,
                create_shipment_automatically = '',
                latest_activity = '',
                latest_status_event = '',
                shipping_rate_id = 56,
                csv_upload_id = 56,
                carrier_id = 56,
                name = '',
                carrier_service_code = '',
                require_drop_point = True,
                visible_for = 56,
                service_attributes = [
                    ''
                    ],
                dimensions = '',
                add_ons = [
                    ''
                    ],
                is_return = True,
                carriers_email = True,
                comment_map = '',
                reference_map = '',
                carriers_sms = True,
                dutiable = True,
                is_hidden = True,
                click_collect = True,
                reference = '',
                default_colli_type = '',
                sender_address_id = 56,
                return_address_id = 56,
                invoice_settings = '',
                shadow_booking_keep_labels = True,
                shadow_booking_keep_documents = True,
                ignore_rate_quote_validation = True,
                custom_message = '',
                regions = '',
                uuid = '',
                approved = True,
                is_online = True,
                last_connected = '',
                prevent_multiple_shipments = True,
                comment = '',
                service_code = '',
                packages = [
                    openapi_client.models.packages.packages(
                        weight = 1.337, 
                        weight_unit = 'g', 
                        dimensions = '', 
                        service_attributes = '', 
                        add_ons = '', 
                        colli_type = '', 
                        predefined_barcode = '', )
                    ],
                pickup_address = openapi_client.models.pickup_address.pickup_address(),
                return_address = openapi_client.models.return_address.return_address(),
                sms_notification = '',
                email_notification = '',
                included_documents = '',
                tracking_links = [
                    openapi_client.models.shipments_tracking_links_inner.shipments_tracking_links_inner(
                        url = '', 
                        number = '', 
                        latest_transit_event = '', 
                        tracking_events = '', )
                    ],
                fulfill_immediately = '',
                original_shipment_id = 56,
                send_time = '',
                latest_update_time = '',
                supports_updates = '',
                additional_attributes = '',
                cost_price = 1.337,
                sales_price = 1.337,
                manual_order_shipment_creation = '',
                carrier_type_name = '',
                carrier_alias = '',
                shadow_booking_as_parent = '',
                document_template = '',
                omit_print = True,
                original_shipment = '',
                pickup_instruction = '',
                pickup_location_close_time = '',
                pickup_time = '',
                shipping_address = '',
                carrier = '',
                return_lines = [
                    ''
                    ],
                secret = '',
                default_locale = '',
                mail_locales = '',
                images = '',
                purpose = 56,
                bcc_mail = '',
                is_prebuilt = True,
                overrides = '',
                defaults = '',
                hook = '',
                whitelisted_languages = '',
                described = ''
            )
        else:
            return ShipmentsIdGet200ResponseIncludedInnerData(
        )
        """

    def testShipmentsIdGet200ResponseIncludedInnerData(self):
        """Test ShipmentsIdGet200ResponseIncludedInnerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
