# coding: utf-8

"""
    Webshipper V2 REST API

       <p>     The Webshipper API is a RESTful JSON API that gives full control over your Webshipper account. The API is scoped to your <em>account name</em>,     and is accessed via the endpoint <em>https://&lt;account name&gt;.api.webshipper.io/v2/</em>. Your <em>account name</em> is the same as you see when you access the Webshipper web UI     at <em>https://&lt;account name&gt;.webshipper.io</em>.   </p>    <p>     This API conforms to the <a href=\"http://jsonapi.org/\">JSON API standard</a> with the following conventions:     <ul>       <li>Resources are identified with the attribute <code>id</code>, which is a server-side generated sequential integer</li>       <li>Resource types are pluralised and underscored, like <code>order_lines</code></li>       <li>The API has a fixed page limit of 30 records. To fetch more records use the query parameter <code>page[number]</code></li>       <li>All resources have the attributes <code>created_at</code> and <code>updated_at</code> which are ISO 8601 timestamps like <code>2018-03-07T14:01:18.000Z</code> </li>       <li>All country codes are <a href=\"https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2\">ISO 3166-1 alpha-2</a> codes</li>     </ul>   </p>     <p> It is also possible to download the documentation in the OpenAPI 3.0 <a href=\"?download_openapi=1\">here</a> </p>    <div class=\"alert alert-info\">     <i class=\"fa fa-info mr-2\"></i>     Webshipper <em>strongly</em> recommends using a client library for utilising this API. Refer to jsonapi.org's list of     <a href=\"http://jsonapi.org/implementations/#client-libraries\">jsonapi.org's list of client libraries</a> to find one for your language.   </div> 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LocalAttrs(BaseModel):
    """
    LocalAttrs
    """ # noqa: E501
    attr_name: Optional[StrictStr] = Field(default=None, description="Visible name of the attribute")
    attr_key: Optional[StrictStr] = Field(default=None, description="Key for the attribute. Used by the system to read the correct information")
    attr_type: Optional[StrictStr] = Field(default=None, description="Data type. Must be either of the following: <code>string</code>, <code>integer</code> or <code>password</code>")
    is_required: Optional[StrictBool] = Field(default=None, description="Determines if the form should require the attr to be filled")
    description: Optional[StrictStr] = Field(default=None, description="Help text to describe the attribute")
    requirement_type: Optional[StrictInt] = None
    category: Optional[StrictStr] = None
    priority: Optional[StrictInt] = None
    only_visible_on_creation: Optional[StrictBool] = Field(default=None, description="Determines if the form should only be visible when connecting")
    __properties: ClassVar[List[str]] = ["attr_name", "attr_key", "attr_type", "is_required", "description", "requirement_type", "category", "priority", "only_visible_on_creation"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LocalAttrs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LocalAttrs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attr_name": obj.get("attr_name"),
            "attr_key": obj.get("attr_key"),
            "attr_type": obj.get("attr_type"),
            "is_required": obj.get("is_required"),
            "description": obj.get("description"),
            "requirement_type": obj.get("requirement_type"),
            "category": obj.get("category"),
            "priority": obj.get("priority"),
            "only_visible_on_creation": obj.get("only_visible_on_creation")
        })
        return _obj


