# coding: utf-8

"""
    Webshipper V2 REST API

       <p>     The Webshipper API is a RESTful JSON API that gives full control over your Webshipper account. The API is scoped to your <em>account name</em>,     and is accessed via the endpoint <em>https://&lt;account name&gt;.api.webshipper.io/v2/</em>. Your <em>account name</em> is the same as you see when you access the Webshipper web UI     at <em>https://&lt;account name&gt;.webshipper.io</em>.   </p>    <p>     This API conforms to the <a href=\"http://jsonapi.org/\">JSON API standard</a> with the following conventions:     <ul>       <li>Resources are identified with the attribute <code>id</code>, which is a server-side generated sequential integer</li>       <li>Resource types are pluralised and underscored, like <code>order_lines</code></li>       <li>The API has a fixed page limit of 30 records. To fetch more records use the query parameter <code>page[number]</code></li>       <li>All resources have the attributes <code>created_at</code> and <code>updated_at</code> which are ISO 8601 timestamps like <code>2018-03-07T14:01:18.000Z</code> </li>       <li>All country codes are <a href=\"https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2\">ISO 3166-1 alpha-2</a> codes</li>     </ul>   </p>     <p> It is also possible to download the documentation in the OpenAPI 3.0 <a href=\"?download_openapi=1\">here</a> </p>    <div class=\"alert alert-info\">     <i class=\"fa fa-info mr-2\"></i>     Webshipper <em>strongly</em> recommends using a client library for utilising this API. Refer to jsonapi.org's list of     <a href=\"http://jsonapi.org/implementations/#client-libraries\">jsonapi.org's list of client libraries</a> to find one for your language.   </div> 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OrderLines(BaseModel):
    """
    OrderLines
    """ # noqa: E501
    sku: Optional[StrictStr] = Field(default=None, description="Stock Keeping Unit of the order line")
    description: Optional[StrictStr] = Field(default=None, description="Description of the goods")
    quantity: Optional[StrictInt] = Field(default=None, description="Quantity of goods")
    location: Optional[StrictStr] = Field(default=None, description="The warehouse location of the items.")
    tarif_number: Optional[StrictStr] = Field(default=None, description="HS Tarif code for paperless customs")
    country_of_origin: Optional[StrictStr] = Field(default=None, description="The country of origin of the goods.")
    unit_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The unit price of goods in the currency of the order")
    package_id: Optional[StrictInt] = Field(default=None, description="Whether the items are associated with a parcel of a shipment.")
    discounted_unit_price: Optional[StrictStr] = Field(default=None, description="The unit price after discounts has been applied in the currency of the order")
    discount_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The discount for the order line, in the type given by discount_type")
    discount_type: Optional[StrictInt] = Field(default=None, description="The type of discount, eg. percent or fixed")
    vat_percent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The VAT rate in percentage.")
    order_id: Optional[StrictInt] = None
    status: Optional[StrictInt] = Field(default=None, description="Possible enum values: pending, dispatched or returned")
    ext_ref: Optional[StrictStr] = Field(default=None, description="External reference of the order line.")
    weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Weight per unit.")
    weight_unit: Optional[StrictStr] = Field(default=None, description="Weight unit. Possible values: <code>oz</code>, <code>g</code>, <code>lbs</code>, <code>kg</code>. Defaults to <code>g</code>")
    created_at: Optional[StrictStr] = Field(default=None, description="The time when the resource was created")
    updated_at: Optional[StrictStr] = Field(default=None, description="The time when resource was last updated or when it was created if it was never updated")
    is_virtual: Optional[StrictBool] = None
    dangerous_goods_details: Optional[Union[str, Any]] = Field(default=None, description="Optional object of key value pairs used for providing information of dangerous goods. For use with DGOffice, use keys: article_no, package_type_id and packaging_instruction_type.")
    __properties: ClassVar[List[str]] = ["sku", "description", "quantity", "location", "tarif_number", "country_of_origin", "unit_price", "package_id", "discounted_unit_price", "discount_value", "discount_type", "vat_percent", "order_id", "status", "ext_ref", "weight", "weight_unit", "created_at", "updated_at", "is_virtual", "dangerous_goods_details"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderLines from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OrderLines from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sku": obj.get("sku"),
            "description": obj.get("description"),
            "quantity": obj.get("quantity"),
            "location": obj.get("location"),
            "tarif_number": obj.get("tarif_number"),
            "country_of_origin": obj.get("country_of_origin"),
            "unit_price": obj.get("unit_price"),
            "package_id": obj.get("package_id"),
            "discounted_unit_price": obj.get("discounted_unit_price"),
            "discount_value": obj.get("discount_value"),
            "discount_type": obj.get("discount_type"),
            "vat_percent": obj.get("vat_percent"),
            "order_id": obj.get("order_id"),
            "status": obj.get("status"),
            "ext_ref": obj.get("ext_ref"),
            "weight": obj.get("weight"),
            "weight_unit": obj.get("weight_unit"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "is_virtual": obj.get("is_virtual"),
            "dangerous_goods_details": obj.get("dangerous_goods_details")
        })
        return _obj


