# coding: utf-8

"""
    Webshipper V2 REST API

       <p>     The Webshipper API is a RESTful JSON API that gives full control over your Webshipper account. The API is scoped to your <em>account name</em>,     and is accessed via the endpoint <em>https://&lt;account name&gt;.api.webshipper.io/v2/</em>. Your <em>account name</em> is the same as you see when you access the Webshipper web UI     at <em>https://&lt;account name&gt;.webshipper.io</em>.   </p>    <p>     This API conforms to the <a href=\"http://jsonapi.org/\">JSON API standard</a> with the following conventions:     <ul>       <li>Resources are identified with the attribute <code>id</code>, which is a server-side generated sequential integer</li>       <li>Resource types are pluralised and underscored, like <code>order_lines</code></li>       <li>The API has a fixed page limit of 30 records. To fetch more records use the query parameter <code>page[number]</code></li>       <li>All resources have the attributes <code>created_at</code> and <code>updated_at</code> which are ISO 8601 timestamps like <code>2018-03-07T14:01:18.000Z</code> </li>       <li>All country codes are <a href=\"https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2\">ISO 3166-1 alpha-2</a> codes</li>     </ul>   </p>     <p> It is also possible to download the documentation in the OpenAPI 3.0 <a href=\"?download_openapi=1\">here</a> </p>    <div class=\"alert alert-info\">     <i class=\"fa fa-info mr-2\"></i>     Webshipper <em>strongly</em> recommends using a client library for utilising this API. Refer to jsonapi.org's list of     <a href=\"http://jsonapi.org/implementations/#client-libraries\">jsonapi.org's list of client libraries</a> to find one for your language.   </div> 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DropPoints(BaseModel):
    """
    DropPoints
    """ # noqa: E501
    drop_point_id: Optional[StrictStr] = Field(default=None, description="The carriers ID of the drop point.")
    name: Optional[StrictStr] = Field(default=None, description="Name of the drop point")
    address_1: Optional[StrictStr] = Field(default=None, description="Address line 1 of the drop point")
    address_2: Optional[StrictStr] = Field(default=None, description="Address line 2 of the drop point")
    zip: Optional[StrictStr] = Field(default=None, description="Zip code for the drop point")
    city: Optional[StrictStr] = Field(default=None, description="City for the drop point")
    country_code: Optional[StrictStr] = Field(default=None, description="Country Code for the drop point. ISO 3166-1 Alfa 2 ")
    state: Optional[StrictStr] = Field(default=None, description="State code. ISO 3166-2 Alfa 2")
    phone: Optional[StrictStr] = Field(default=None, description="Phone of the drop point")
    carrier_code: Optional[StrictStr] = Field(default=None, description="Text base code to identify the carrier of the drop point ( not mandatory )")
    routing_code: Optional[StrictStr] = Field(default=None, description="Routing code for the drop point.")
    longitude: Optional[StrictStr] = Field(default=None, description="Longitude")
    latitude: Optional[StrictStr] = Field(default=None, description="Latitude")
    created_at: Optional[StrictStr] = Field(default=None, description="The time when the resource was created")
    updated_at: Optional[StrictStr] = Field(default=None, description="The time when resource was last updated or when it was created if it was never updated")
    opening_hours: Optional[StrictStr] = Field(default=None, description="Opening hours for the drop point. Days are 0-indexed, starting with Monday as 0")
    __properties: ClassVar[List[str]] = ["drop_point_id", "name", "address_1", "address_2", "zip", "city", "country_code", "state", "phone", "carrier_code", "routing_code", "longitude", "latitude", "created_at", "updated_at", "opening_hours"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DropPoints from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
                "opening_hours",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DropPoints from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "drop_point_id": obj.get("drop_point_id"),
            "name": obj.get("name"),
            "address_1": obj.get("address_1"),
            "address_2": obj.get("address_2"),
            "zip": obj.get("zip"),
            "city": obj.get("city"),
            "country_code": obj.get("country_code"),
            "state": obj.get("state"),
            "phone": obj.get("phone"),
            "carrier_code": obj.get("carrier_code"),
            "routing_code": obj.get("routing_code"),
            "longitude": obj.get("longitude"),
            "latitude": obj.get("latitude"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "opening_hours": obj.get("opening_hours")
        })
        return _obj


