# coding: utf-8

"""
    Webshipper V2 REST API

       <p>     The Webshipper API is a RESTful JSON API that gives full control over your Webshipper account. The API is scoped to your <em>account name</em>,     and is accessed via the endpoint <em>https://&lt;account name&gt;.api.webshipper.io/v2/</em>. Your <em>account name</em> is the same as you see when you access the Webshipper web UI     at <em>https://&lt;account name&gt;.webshipper.io</em>.   </p>    <p>     This API conforms to the <a href=\"http://jsonapi.org/\">JSON API standard</a> with the following conventions:     <ul>       <li>Resources are identified with the attribute <code>id</code>, which is a server-side generated sequential integer</li>       <li>Resource types are pluralised and underscored, like <code>order_lines</code></li>       <li>The API has a fixed page limit of 30 records. To fetch more records use the query parameter <code>page[number]</code></li>       <li>All resources have the attributes <code>created_at</code> and <code>updated_at</code> which are ISO 8601 timestamps like <code>2018-03-07T14:01:18.000Z</code> </li>       <li>All country codes are <a href=\"https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2\">ISO 3166-1 alpha-2</a> codes</li>     </ul>   </p>     <p> It is also possible to download the documentation in the OpenAPI 3.0 <a href=\"?download_openapi=1\">here</a> </p>    <div class=\"alert alert-info\">     <i class=\"fa fa-info mr-2\"></i>     Webshipper <em>strongly</em> recommends using a client library for utilising this API. Refer to jsonapi.org's list of     <a href=\"http://jsonapi.org/implementations/#client-libraries\">jsonapi.org's list of client libraries</a> to find one for your language.   </div> 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from webshipperv2.models.additional_attributes_id_get200_response_relationships_order import AdditionalAttributesIdGet200ResponseRelationshipsOrder
from webshipperv2.models.edis_id_get200_response_relationships_shipment import EdisIdGet200ResponseRelationshipsShipment
from webshipperv2.models.return_refund_methods_id_get200_response_relationships_portal import ReturnRefundMethodsIdGet200ResponseRelationshipsPortal
from webshipperv2.models.returns_id_get200_response_relationships_refund_method import ReturnsIdGet200ResponseRelationshipsRefundMethod
from webshipperv2.models.returns_id_get200_response_relationships_shipping_method import ReturnsIdGet200ResponseRelationshipsShippingMethod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ReturnsIdGet200ResponseRelationships(BaseModel):
    """
    ReturnsIdGet200ResponseRelationships
    """ # noqa: E501
    order: Optional[AdditionalAttributesIdGet200ResponseRelationshipsOrder] = None
    portal: Optional[ReturnRefundMethodsIdGet200ResponseRelationshipsPortal] = None
    shipping_method: Optional[ReturnsIdGet200ResponseRelationshipsShippingMethod] = None
    refund_method: Optional[ReturnsIdGet200ResponseRelationshipsRefundMethod] = None
    shipment: Optional[EdisIdGet200ResponseRelationshipsShipment] = None
    __properties: ClassVar[List[str]] = ["order", "portal", "shipping_method", "refund_method", "shipment"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReturnsIdGet200ResponseRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of portal
        if self.portal:
            _dict['portal'] = self.portal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping_method
        if self.shipping_method:
            _dict['shipping_method'] = self.shipping_method.to_dict()
        # override the default output from pydantic by calling `to_dict()` of refund_method
        if self.refund_method:
            _dict['refund_method'] = self.refund_method.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipment
        if self.shipment:
            _dict['shipment'] = self.shipment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ReturnsIdGet200ResponseRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "order": AdditionalAttributesIdGet200ResponseRelationshipsOrder.from_dict(obj.get("order")) if obj.get("order") is not None else None,
            "portal": ReturnRefundMethodsIdGet200ResponseRelationshipsPortal.from_dict(obj.get("portal")) if obj.get("portal") is not None else None,
            "shipping_method": ReturnsIdGet200ResponseRelationshipsShippingMethod.from_dict(obj.get("shipping_method")) if obj.get("shipping_method") is not None else None,
            "refund_method": ReturnsIdGet200ResponseRelationshipsRefundMethod.from_dict(obj.get("refund_method")) if obj.get("refund_method") is not None else None,
            "shipment": EdisIdGet200ResponseRelationshipsShipment.from_dict(obj.get("shipment")) if obj.get("shipment") is not None else None
        })
        return _obj


